export const generatePDF = async (prompts, emotion) => {
  if (typeof window === 'undefined') return;

  const html2pdf = (await import('html2pdf.js')).default;

  const element = document.createElement('div');
  element.innerHTML = `
    <div style="font-family: 'Playfair Display', serif; padding: 20px;">
      <h1 style="color: #3F3F3F; font-size: 24px; margin-bottom: 20px;">InnerPrompt Journal</h1>
      <p style="color: #666; margin-bottom: 30px;">Emotion: ${emotion}</p>
      <div style="margin-bottom: 20px;">
        ${prompts.map((prompt, index) => `
          <div style="margin-bottom: 15px;">
            <p style="color: #3F3F3F; font-size: 16px;">${index + 1}. ${prompt}</p>
          </div>
        `).join('')}
      </div>
      <p style="color: #666; font-size: 12px; margin-top: 30px;">Generated by InnerPrompt</p>
    </div>
  `;

  const opt = {
    margin: 1,
    filename: `innerprompt-${emotion}-${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
  };

  try {
    await html2pdf().set(opt).from(element).save();
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return false;
  }
}; 